import {
  FILTER_ALL_EN,
  FILTER_ALL_RU,
  FILTER_COMPLETED_EN,
  FILTER_COMPLETED_RU,
  FILTER_FAVORITE_EN,
  FILTER_FAVORITE_RU,
  FILTER_NOT_COMPLETED_EN,
  FILTER_NOT_COMPLETED_RU,
} from './texts';

export const filterTypes = [
  { label: FILTER_ALL_RU, key: FILTER_ALL_EN },
  { label: FILTER_COMPLETED_RU, key: FILTER_COMPLETED_EN },
  { label: FILTER_NOT_COMPLETED_RU, key: FILTER_NOT_COMPLETED_EN },
  { label: FILTER_FAVORITE_RU, key: FILTER_FAVORITE_EN },
];

export const taskTypes = [
  { label: FILTER_COMPLETED_RU, key: FILTER_COMPLETED_EN },
  { label: FILTER_NOT_COMPLETED_RU, key: FILTER_NOT_COMPLETED_EN },
];

export const SCROLL_LOAD_THRESHOLD_MESSAGE = 5;

export const SCROLL_LOAD_DELAY = 300;
